[metadata]
name = "tree_sitter_tags"
description = "Select from tree-sitter-tags"
requirements = ["tree_sitter_tags"]

[source]
command = "tree_sitter_tags | perl -lane 'print if $F[1] =~ \"(function|class|method)\"'"
display = "{split:\\t:0|pad:40: :left} {split:\\t:1|pad:10: :left} {split:\\t:3}"
output = "{split:\\t:0}"

[preview]
command = "bat --color=always --style=numbers --highlight-line {split:\\t:4} {split:\\t:3}"
offset = "{split:\\t:4}"

[keybindings]
enter = "actions:edit"

[actions.edit]
description = "open in editor"
command = "${EDITOR:-vim} +{split:\\t:4} '{split:\\t:3}'"
shell = "bash"
mode = "execute"
