[default_session]
# startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "pgcli calibracion"
path = "~/workspace/sql"
startup_command = "pgcli -D eolica_calibracion"

[[session]]
name = "ssh to host"
startup_command = "read -p 'Indica el host: ' ; ssh $REPLY"

[[session]]
name = "sesh config"
path = "~/workspace/dotfiles"
startup_command = "nvim -c ':e config/sesh.toml' "
preview_command = "batcat --color=always config/sesh.toml"

[[session]]
name = "k9s prod"
path = "~/workspace/kubernetes-services"
startup_command = "k9s --context=user-dyo-context"
