[default_session]
# startup_command = "nvim -c ':Telescope find_files'"
startup_command = 'nvim'

[[session]]
name = "pgcli"
path = "~/workspace/sql"
startup_command = '''perl -lne 'print if /^\[alias_dsn\]/../\[(?!alias_dsn)/' ~/.config/pgcli/config | grep = | cut -d= -f 1 | fzf | xargs -roI ARG sh -c "tmux rename 'pgcli ARG'; pgcli -D ARG"'''

[[session]]
name = "ssh to eolo/portatil/cal"
startup_command = "read -p 'Indica el host: ' ; tmux rename \"ssh $REPLY\"; ssh $REPLY"

[[session]]
name = "sesh config"
path = "~/workspace/dotfiles"
startup_command = "nvim -c ':e config/sesh.toml' "
preview_command = "batcat --color=always config/sesh.toml"

[[session]]
name = "tmux config"
path = "~/workspace/dotfiles"
startup_command = "nvim -c ':e tmux.conf' "
preview_command = "batcat --color=always tmux.conf"

[[session]]
name = "k9s prod"
path = "~/workspace/kubernetes-services"
startup_command = "k9s --context=user-dyo-context"

[[session]]
name = "k9s staging"
path = "~/workspace/kubernetes-services"
startup_command = "k9s --context=user-dyo-staging-context"
