#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
[default_session]
startup_command = "tv"

[[session]]
name = "pgcli"
path = "~/workspace/sql"
startup_command = "tv pgcli -k=\"enter='connect_and_rename_tmux_session'\""

[[session]]
name = "ssh"
startup_command = "tv ssh_server -k=\"enter='connect_and_rename_tmux_session'\""

[[session]]
name = "sesh config"
path = "~/workspace/dotfiles"
startup_command = "nvim -c ':e config/sesh.toml' "
preview_command = "batcat --color=always config/sesh.toml"

[[session]]
name = "tmux config"
path = "~/workspace/dotfiles"
startup_command = "nvim -c ':e tmux.conf' "
preview_command = "batcat --color=always tmux.conf"

[[session]]
name = "k9s prod"
path = "~/workspace/kubernetes-services"
startup_command = "k9s --context=oidc-production-context"

[[session]]
name = "k9s staging"
path = "~/workspace/kubernetes-services"
startup_command = "k9s --context=oidc-staging-context"

[[session]]
name = "tareas desde query"
path = "~/workspace/devops-toolbox"
startup_command = "__atuin_history tareas_desde_query"

[[session]]
name = "command"
path = "~/workspace"
disable_startup_command = true
